package dev.nucleusframework.desktop.application.internal.analyzer

/** Explicit exclusions applied to metadata generated by the bytecode analyzer. */
internal data class StaticMetadataExclusions(
    val typeMatcher: TypePrefixMatcher,
    val resourceGlobs: Set<String>,
) {
    constructor(
        typePrefixes: Set<String>,
        resourceGlobs: Set<String>,
    ) : this(
        typeMatcher = TypePrefixMatcher(typePrefixes),
        resourceGlobs = resourceGlobs.map { it.trim() }.filter(String::isNotEmpty).toSet(),
    )
}

/** Boundary-aware matcher for Java package, class, and nested-class names. */
internal class TypePrefixMatcher(prefixes: Set<String>) {
    private val normalizedPrefixes =
        prefixes
            .asSequence()
            .map(String::trim)
            .map { it.trimEnd('.', '$') }
            .filter(String::isNotEmpty)
            .toSet()

    fun matches(typeName: String): Boolean {
        val elementType = typeName.removeArraySuffixes()
        return normalizedPrefixes.any { prefix ->
            elementType == prefix ||
                elementType.startsWith("$prefix.") ||
                elementType.startsWith("${prefix}$")
        }
    }
}

/**
 * Removes excluded owners and signatures from an analyzer result.
 *
 * Classes are also skipped during the bytecode walk. This final pass handles metadata read
 * outside that walk (for example service descriptors) and signatures on otherwise retained
 * owners that mention an excluded platform type.
 */
internal fun AnalysisResult.excluding(exclusions: StaticMetadataExclusions): AnalysisResult =
    copy(
        reflectionEntries = reflectionEntries.mapNotNullTo(mutableSetOf()) { it.excluding(exclusions.typeMatcher) },
        jniEntries = jniEntries.mapNotNullTo(mutableSetOf()) { it.excluding(exclusions.typeMatcher) },
        resourcePatterns = resourcePatterns.filterNotTo(mutableSetOf()) { it.glob in exclusions.resourceGlobs },
        serviceLoaderEntries =
            serviceLoaderEntries.mapNotNullTo(mutableSetOf()) { it.excluding(exclusions.typeMatcher) },
        projectClassEntries =
            projectClassEntries.mapNotNullTo(mutableSetOf()) { it.excluding(exclusions.typeMatcher) },
    )

private fun ReflectionEntry.excluding(matcher: TypePrefixMatcher): ReflectionEntry? {
    if (matcher.matches(type)) return null

    val retainedMethods = methods.filterNotTo(mutableSetOf()) { it.mentions(matcher) }
    if (methods.isNotEmpty() && retainedMethods.isEmpty() && !hasNonMethodRegistration()) return null
    return copy(methods = retainedMethods)
}

private fun JniEntry.excluding(matcher: TypePrefixMatcher): JniEntry? {
    if (matcher.matches(type)) return null

    val retainedMethods = methods.filterNotTo(mutableSetOf()) { it.mentions(matcher) }
    if (methods.isNotEmpty() && retainedMethods.isEmpty() && fields.isEmpty() && !jniAccessible) return null
    return copy(methods = retainedMethods)
}

private fun ReflectionEntry.hasNonMethodRegistration(): Boolean =
    fields.isNotEmpty() ||
        allDeclaredFields ||
        allDeclaredMethods ||
        allDeclaredConstructors ||
        allPublicFields ||
        allPublicMethods ||
        allPublicConstructors ||
        unsafeAllocated

private fun MethodSignature.mentions(matcher: TypePrefixMatcher): Boolean = parameterTypes.any(matcher::matches)

private fun String.removeArraySuffixes(): String {
    var result = this
    while (result.endsWith("[]")) {
        result = result.removeSuffix("[]")
    }
    return result
}
